version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: library9_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=library9
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: library9_api
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/library9
    depends_on:
      - db

  locust:
    image: locustio/locust
    ports:
      - "8089:8089"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --host http://app:8000
    depends_on:
      - app